### ISSUE TITLE
wget tidyp link is invalid

### ISSUE THREAD

**Issue by Cabalist** [tlvince/w3c-validator-guide#15]
The cloud.github link for tidyp seems to no longer work I get an SSL error.

This is the problematic line:
`wget https://cloud.github.com/downloads/petdance/tidyp/tidyp-1.04.tar.gz`

This following command works fine:

`wget https://github.com/petdance/tidyp/archive/1.04.tar.gz`

**Comment by Cabalist** [comment]
This also causes the next command to be:
```tar -xzf 1.04.tar.gz```

instead of:
```tar -xzf tidyp-1.04.tar.gz```

**Comment by tlvince** [comment]
Closed by #18.
